// 根布局：加载字体和全局样式，所有页面共用。
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// 加载无衬线和等宽字体，通过 CSS 变量供样式使用。
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 页面标题和描述，显示在浏览器标签页中。
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 用 html 和 body 包裹每个页面的内容。
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
